# Generated by Django 6.0.1 on 2026-01-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='register',
            name='Password',
            field=models.CharField(max_length=128),
        ),
    ]
