# Generated by Django 6.0.1 on 2026-02-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0002_alter_register_mobile_alter_register_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Mobile', models.CharField(max_length=10)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Reason', models.TextField()),
            ],
        ),
    ]
